### ISSUE TITLE
Special characters not deployed properly

### ISSUE THREAD

**Issue by ndorotte** [fundacionjala/enforce-gradle-plugin#131]
We have a file containing special characters (encoding utf-8).
![image](https://cloud.githubusercontent.com/assets/2373097/8188898/44061050-141e-11e5-9f33-d3e9db4924f7.png)

When the file is deployed to the organization, however, these special characters get replaced with "??????".
![image](https://cloud.githubusercontent.com/assets/2373097/8188924/700abd68-141e-11e5-8176-4e2988f85396.png)

This causes some of our unit tests to fail.

**Comment by rodrigouz** [comment]
Hi @ndorotte,
This was fixed in the 1.0.5 version.

**Comment by ndorotte** [comment]
Great! You guys are on a roll!
