### ISSUE TITLE
@isTest annotation should be case insensitive

### ISSUE THREAD

**Issue by ndorotte** [fundacionjala/enforce-gradle-plugin#132]
When running all tests using async=true, only tests containing @isTest are being executed.
We had some test cases containing @IsTest (note the uppercase "I") that were being ignored.

RunTestTask.groovy, line 411, should probably use containsIgnoreCase(IS_TEST) instead of contains(IS_TEST) given that Apex is case insensitive.

**Comment by ndorotte** [comment]
You may also want to consider leveraging the testLevel option of the Metadata API deploy() method to run all non-managed unit tests (RunLocalTests):
https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy.htm#deploy_options

**Comment by marcocdlv** [comment]
HI @ndorotte,
The bug #132 was fixed at 1.0.5 version

**Comment by ndorotte** [comment]
Great. Thanks!

**Comment by marcocdlv** [comment]
You're welcome
