### ISSUE TITLE
There is not an option to disable subcomponents deletion on Update command.

### ISSUE THREAD

**Issue by naverus** [fundacionjala/enforce-gradle-plugin#171]
When file teacking feature has subcomponents to delete, by default Update command always deletes them. There are cases where it is not necessary to delete them and it would be useful an option to disable this default operation.

E.G.

```
enforce{
    filetracking.delete.subcomponents = 'none'
}
```

```
enforce{
    filetracking.delete.subcomponents = 'fields, fieldsets, validationrules'
}
```

**Comment by MarceloEof** [comment]
This feature meets the criterion defined, but I think that  customize the subcomponents selectors a name's level
