### ISSUE TITLE
Make configurable the Salesforce Api version instead of 32.0v

### ISSUE THREAD

**Issue by jhonny-villarroel** [fundacionjala/enforce-gradle-plugin#183]
Hi,
first congratulations for this amazing tool :)
Well in my team we decide to upgrade api version from 32.0  to 34.0v which is configured in the package.xml and when we execute the command deploy we have the following error:

![errorapiversion](https://cloud.githubusercontent.com/assets/2737098/8935633/b8ee3dca-351b-11e5-95e3-f65686ebda98.png)

Can you help us in that please

**Comment by marcocdlv** [comment]
Hi @jhonny-villarroel 
This enhancement was added at 1.0.8 version.

**Comment by jhonny-villarroel** [comment]
Thanks!!
