### ISSUE TITLE
Add a new task to show all credentials from project directory and home directory.

### ISSUE THREAD

**Issue by marcocdlv** [fundacionjala/enforce-gradle-plugin#187]

**Comment by marcocdlv** [comment]
This task should be able to show credential by id, and all credentials

**Comment by Ariel-Patino** [comment]
Now executing getCredentials task is posible see credentials registered on Enforce listed in the next way: 
    -ID default  
    -User: user@login.com
    -Type: Sandbox
This feature is available from version 1.0.9
