### ISSUE TITLE
Jenkins report plugin shows code coverage  0% 

### ISSUE THREAD

**Issue by jhonny-villarroel** [fundacionjala/enforce-gradle-plugin#218]
Hi Guys,

I have some problem with my Jenkins report code coverage plugin:
when execute gradle task:
`gradle runTest`

in the build/report/index.html the code coverage is 0% but all of my unit test passed as you can see below:
![report error](https://cloud.githubusercontent.com/assets/2737098/9361617/41d91c36-466a-11e5-8cd3-08dad9189a9d.png)

I already update the last version 1.1.0 but we still have the problem.

Regards,
Jhonny Villarroel

**Comment by marcocdlv** [comment]
This issue is fixed at 1.1.1 version
