### ISSUE TITLE
Deploy task is not available for windows environment

### ISSUE THREAD

**Issue by marcelogaray** [fundacionjala/enforce-gradle-plugin#227]
![selection_309](https://cloud.githubusercontent.com/assets/3451190/9532798/d4546b48-4cdb-11e5-84a6-c99e52961ff9.png)

Version 1.1.1

**Comment by marcocdlv** [comment]
Hi Marcelo, 

I reviewed this, the problem is that in build.gradle file there is a task called help, for so Deploy doesn't work because this task has parameter called help to show you information about this task,

Best regards

**Comment by marcelogaray** [comment]
great thank you!
