### ISSUE TITLE
Running uninstallPackage only prints help

### ISSUE THREAD

**Issue by ndorotte** [fundacionjala/enforce-gradle-plugin#233]
When I try to execute the following command with version 1.1.1 of the plugin, a help message explaining how to use the command is displayed but nothing else is executed. Am I missing something?

Command:
<pre>
$ gradle uninstallPackage -Ppkg.namespace=pros_q2w -PcredentialId=20demo.com
</pre>

Output:
<pre>
:uninstallPackage
********************************************************************************

                             uninstallPackage task

********************************************************************************

Description   :
    Uninstalls a management package

Documentation : 
    http://fundacionjala.github.io/enforce-gradle-plugin/docs/package-management

Parameters :
    -Ppkg.namespace : Package name to install
        > gradle uninstallPackage -Ppkg.namespace=al

********************************************************************************

BUILD SUCCESSFUL

Total time: 7.733 secs
</pre>

**Comment by marcocdlv** [comment]
Hi @ndorotte ,

I'm trying reproduce this issue, Could you send me your build.gradle file, please?, perhaps into build.gradle file there is a task called help for so when you execute  that command it shows you information about this task,

regards

**Comment by ndorotte** [comment]
There is indeed a task called `help` in my build.gradle. If I remove it, then the Enforce task is executed correctly.

**Comment by marcocdlv** [comment]
Then the package is installed correctly, right? What happen when you try uninstall a package? Those tasks are working correctly?

**Comment by ndorotte** [comment]
Yes, the package is installed correctly. I had to install it manually because the installPackage task doesn't seem to work for me either.
Even with version 1.1.1, I can't seem to make uninstallPackage work.

Not sure if it matters but the org I'm trying to uninstall from has a custom domain: ndorotte-20demo-dev-ed.

**Comment by marcocdlv** [comment]
I will work in those issues, thanks for your information
regards
