### ISSUE TITLE
uninstallPackage does not uninstall package

### ISSUE THREAD

**Issue by ndorotte** [fundacionjala/enforce-gradle-plugin#234]
In version 1.0.5, the uninstallPackage task does not seem to be working. The output says the package has been uninstall successfully but I still see it in my org.
I can't test with the latest version because in that version it only prints the help message.

Command:
<pre>
$ gradle uninstallPackage -Ppkg.namespace=pros_q2w -PcredentialId=20demo.com
</pre>

Output:
<pre>
:uninstallPackage
___________________________________________  
	Username: ndorotte@20demo.com           
	Login type: login
___________________________________________  

Verifying installed package 'pros_q2w' ...
Starting retrieve...
Waiting for retrieve result...
Retrieve result completed
    [unzip] Expanding: /Users/ndorotte/PROS/q2w/automation/build/installedpkgsresult/installedPkgs.zip into /Users/ndorotte/PROS/q2w/automation/build/installedpkgsresult
Installed package 'pros_q2w' found.
Starting deploy...
[                                                  ]   0%     
The files were successfully deployed

Uninstall package 'pros_q2w' success.

BUILD SUCCESSFUL

Total time: 3 mins 5.465 secs
</pre>

**Comment by marcocdlv** [comment]
Hi @ndorotte,

This bug was fixed at 1.1.2 version, Could you review that, please?

The best regards

**Comment by ndorotte** [comment]
uninstallPackage works now. Thanks for fixing this so fast!

**Comment by naverus** [comment]
Great !!!

**Comment by marcocdlv** [comment]
You are welcome
