### ISSUE TITLE
Issue while setting up gradle

### ISSUE THREAD

**Issue by asingh06** [fundacionjala/enforce-gradle-plugin#296]
Going through the doc I am setting up the gradle to use with jenkins. Here is my build.gradle file
buildscript {
repositories {
mavenCentral()
jcenter()
}
dependencies {
classpath 'org.fundacionjala.gradle.plugins.enforce:enforce-gradle-plugin:1.1.4'
}
}

apply plugin: 'enforce'

enforce {
srcPath = 'src'
}

running gradle tasks I am getting the error -
* Where:
Build file 'C:\Desktop\testProject\build.gradle' line: 11

* What went wrong:
A problem occurred evaluating root project 'testProject'.
> Failed to apply plugin [id 'enforce']
   > Could not create task of type 'RunTestTask'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

-- On running command gradle -version received following -
 ------------------------------------------------------------
Gradle 3.2.1
------------------------------------------------------------

Build time:   2016-11-22 15:19:54 UTC
Revision:     83b485b914fd4f335ad0e66af9d14aad458d2cc5

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_111 (Oracle Corporation 25.111-b14)
OS:           Windows 7 6.1 amd64

Even if i run command gradle tasks - got the same error 
C:\Desktop\testProject>gradle tasks

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Desktop\testProject\build.gradle' line: 11

* What went wrong:
A problem occurred evaluating root project 'testProject'.
> Failed to apply plugin [id 'enforce']
   > Could not create task of type 'RunTestTask'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 2.584 secs

Could you please help in resolving this issue.

**Comment by ziur** [comment]
Hi, 

Could you please try with gradle 2.x version, we didn't implemented yet the support to 3.x version

**Comment by asingh06** [comment]
Hi,
Tried that still the same error --
Gradle version --
------------------------------------------------------------
Gradle 2.14.1
------------------------------------------------------------

Build time:   2016-07-18 06:38:37 UTC
Revision:     d9e2113d9fb05a5caabba61798bdb8dfdca83719

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_111 (Oracle Corporation 25.111-b14)
OS:           Windows 7 6.1 amd64

----
Error -
* What went wrong:
A problem occurred evaluating root project 'test1'.
> Failed to apply plugin [id 'enforce']
   > Could not create task of type 'RunTestTask'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

**Comment by ziur** [comment]
@asingh06, I will take a look to this.

**Comment by asingh06** [comment]
Thanks, will wait for your response.

**Comment by asingh06** [comment]
any update on this?

**Comment by ziur** [comment]
Yes, it seems the version 1.1.5 is broken, and since gradle 2.14 a class was moved to another package. 
I will work in the fix, meanwhile could you please give try again with build 1.1.4 and gradle 2.13? It should work with this version.
If you any need any help, please let me know.

**Comment by asingh06** [comment]
thank you for the solution, it is working with build 1.1.4 and gradle 2.13.
