### ISSUE TITLE
Upload/Deploy tasks don't upload Reports

### ISSUE THREAD

**Issue by naverus** [fundacionjala/enforce-gradle-plugin#44]
You can use the following steps to validate this bug:

PRE-CONDITIONS:
- Create a folder and a report in an org.

REPRODUCTION STEPS:
- Retrieve them from the org using "gradle retrieve", JIC you have to update your local package.xml file.(please take a look that the reports folder is not retrieved, also another bug)
- Delete them from the org.(Manually)
- Upload them.(gradle deploy/upload/update)

ACTUAL RESULT:
Reports are not retrieved/updated/deployed.

EXPECTED RESULT:
Reports should be handled properly on retrieve, upload, deploy and update tasks.

WORKAROUND:
None

FOUND IN:
Version: 1.0.1

**Comment by alexrv11** [comment]
The same problem it's happen when execute the retrieve task doesn't upload the reports

**Comment by alexrv11** [comment]
The upload, deploy, retrieve, undeploy. and update are working with reports, documents, and dashboard in the Version 1.0.3. You can try to use this version updating the build.gradle in your dependencies.

classpath 'org.fundacionjala.gradle.plugins.enforce:enforce-gradle-plugin:1.0.3'
