### ISSUE TITLE
Validation for deploy/upload tasks should be optional

### ISSUE THREAD

**Issue by mgarnica** [fundacionjala/enforce-gradle-plugin#52]
The validation message that appears for the upload task is kind of annoying, maybe a configuration parameter could be added to ignore those validation messages.

ignoreDeployValidation = true

the parameter will make the message "> Building 0% > :upload Do you want to continue? (y/n)" not to appear when executing the upload task.

Also the Deploy task doesn't seem to have a validation message, it should have.

**Comment by naverus** [comment]
You can add the following configuration to avoid these validations.

enforce {
    srcPath = 'src'
    upload.all = true
    retrieve.all = true
}
