### ISSUE TITLE
Update/Deploy/Undeploy command does not take in account the package.xml info for packaged objects

### ISSUE THREAD

**Issue by naverus** [fundacionjala/enforce-gradle-plugin#60]
If there are custom fields, fieldsets, validation rules or another Object's subcomponent defined for packaged objects, current tasks dont take in account them in the generated package.xml file to deploy changes.
E.G.

Source Code package.xml

```
<member>
<members>mynamespace__MyObject__c.MyCustomField__c</members>
<name>CustomField</name>
</member>
```

Generated package.xml always suscribes just the custom object

```
<member>
<members>mynamespace__MyObject__c</members>
<name>CustomObject</name>
</member>
```

**Comment by marcocdlv** [comment]
HI @naverus ,
Update, upload, deploy and undeploy tasks now are taking in account package.xml file from project directory in version 1.0.4
