### ISSUE TITLE
Update task fails for files that have spaces in their name

### ISSUE THREAD

**Issue by mgarnica** [fundacionjala/enforce-gradle-plugin#94]
this happens on version 1.0.3 for files that have spaces on their names
![image](https://cloud.githubusercontent.com/assets/3143343/7871640/2c38376e-055f-11e5-8514-8673987b817d.png)

**Comment by naverus** [comment]
It means that you have something like this, right?

/src/profiles/My -  CustomProfiles.profile

**Comment by mgarnica** [comment]
yes, something like /src/profiles/My Profile is so cool.profile

**Comment by alexrv11** [comment]
Hi, this issue was solved in the 1.0.4 version. You can try it.
